### ISSUE TITLE
Add hyper parameters in configuration file for prophet model

### ISSUE THREAD

**Issue by iamvishnuks** [xmigrate/xforecast#12]
**Objective**
User should be able to provide the name of the model to use as configuration parameter and input the hyperparameters for that model to tune the predictions by user.
**Outcome**
- [x] Update the configuration file format to include model name and hyper parameters
- [x] Update the fit and predict function to consider the hyper parameters added in configuration file
- [ ] Demo with team showing different hyper parameter configuration for a same metric
- [x] Documentation should be updated

**Comment by WeepingClown13** [comment]
Made the changes except for the demo file and added pull request.
