### ISSUE TITLE
Fix unit test cases

### ISSUE THREAD

**Issue by iamvishnuks** [xmigrate/xforecast#17]
### Objective
To fix the unit test cases issues

**Outcome**
- [x] Add an additional parameter test=False for functions which reads and write to datastores, If the value is set to True then skip reading or writing to the datastore and return the expected outcome. Implement this method in other functions as necessary
- [x] Remove assertion of values given in the config file

**Comment by josukutty** [comment]
Fixed this issue by adding test parameter and removing assertion of values given in the config.
